# permissions for end users to view eventlisteners.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: eventlistener-viewer-role
rules:
- apiGroups:
  - triggers.gitctl.com
  resources:
  - eventlisteners
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - triggers.gitctl.com
  resources:
  - eventlisteners/status
  verbs:
  - get
